### ISSUE TITLE
Filter for multiple locations

### ISSUE THREAD

**Issue by mal-tee** [AdriDevelopsThings/strecken-info-bot#9]
Hi! 

If I understand the german text about filters correctly, all filters must be satisfied for a info to come through, right?

Is there a way to get notified if any of them applies? E.g. I want to get notified for both City + 100 km and City B + 50 km

Thanks!

**Comment by AdriDevelopsThings** [comment]
Hi!

Thats correct. Maybe the user should configure if all filters must be satisfied or just one filter. I'll think about adding this feature.

**Comment by AdriDevelopsThings** [comment]
Done!
